### ISSUE TITLE
Use `AnyComponent` instead of `ComponentFactory` in `mountJsx

### ISSUE THREAD

**Issue by keichinger** [Becklyn/mojave#166]
With Preact 8.4.0 (see PR https://github.com/developit/preact/pull/1249) we should no switch over to `AnyComponent` instead of `ComponentFactory<T>` in order to fix compatibility.

Pretty sure that using `ComponentFactory<T>` was never intended to be used outside of Preact itself.

**Comment by apfelbox** [comment]
As we saw this is not correct – as `h()` still (correctly) expectes a `ComponentFactory`.
